name: my first action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      python-version: [3.9, 3.9] 
  
    steps:
      - uses: actions/checkout@v3
      - name: Setup python version
        uses: actions/setup-python@v2
        with:
         python-version: ${{ matrix.python-version }}
         
      - name: installing python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
        
      - name: python testing
         run:|
          cd src
          python -m pytest addition.py
  
