on  
  push
   - gh-action

jobs:
  setup:
    name: IOS Build & Deploy
    runs-on: macos-13-xlarge
    timeout-minutes: 20
    environment: Protected
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: aws cli check
        run: AWScli
