on:
#   pull_request:
  push:
    branches:
      - main
      - master
      - release*
      - develop

env:
    URL: pandeyak1991
    ECR_REPOSITORY: test


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    # outputs:
    #   imagePushed: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
    
    steps:
     - uses: docker/metadata-action@v4
       id: metadata
       with:
         images: pandeyak1991/${{ github.repository }}
         flavor: suffix=-${{ matrix.platform }}

     - uses: docker/build-push-action@v3
       with:
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}

         
  build-multi-architecture:
   needs:
           - build
   runs-on: ubuntu-latest

   steps:
      - uses: docker/metadata-action@v4
        id: metadata
        with:
         images: pandeyak1991/${{ github.repository }}

      - uses: int128/docker-manifest-create-action@v1
        with:
         tags: ${{ steps.metadata.outputs.tags }}
         suffixes: |
             -amd64
             -arm64     