on:
    workflow_dispatch:
    push:
      branches:
        - main
        - master
        - release*
        - develop
  
env:
      # URL: pandeyak1991
      # ECR_REPOSITORY: test
      REGISTRY_IMAGE: pandeyak1991/test
      # dep: NonProd
      # NonProdEnvName: NonProd
      # ProdEnvName: Prod
  
jobs:
    build:
      runs-on: ubuntu-latest
      outputs:
        NonProdEnvName: ${{ steps.name.outputs.NonProdEnvName }}

      steps:

       - name: Set output
         id: name
         run: echo "NonProdEnvName=NonProd" >> $GITHUB_OUTPUT

       - name: echoing
         run: |
              echo "I'm using variable ${{ steps.name.outputs.NonProdEnvName }}"

      

        
    job2:
      name: pushing-merge
      runs-on: ubuntu-latest
      environment:  
        name: ${{ needs.build.outputs.NonProdEnvName }}
      needs:
         - build
      concurrency:
          group: ${{ needs.build.outputs.NonProdEnvName }}
        
      outputs:
          ProdEnvName: ${{ steps.name.outputs.ProdEnvName }}

      steps:
         - name: ecr login
           id: login-ecr
           run: |
              echo "I'm using variable ${{ needs.build.outputs.NonProdEnvName}}"
         - name: Set output
           id: name
           run: echo "ProdEnvName=Prod" >> $GITHUB_OUTPUT
             
####
    job3:
      name: job3-merge
      runs-on: ubuntu-latest
      environment:  
       name: ${{ needs.job2.outputs.ProdEnvName }}
      needs:
        - job2
      concurrency:
       group: ${{ needs.job2.outputs.ProdEnvName }}
      steps:
       - name: ecr login
         id: login-ecr
         run: |
          echo "I'm using variable ${{ needs.build.outputs.ProdEnvName}}"
        