on:
#   pull_request:
  push:
    branches:
      - main
      - master
      - release*
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      uses: docker/build-push-action@v4
      with:
          tags: test_image:latest
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/test.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: docker-image
          path: /tmp/test.tar
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
            name: docker-image
            path: /tmp
    - name: Load Docker image
      run: |
           docker load --input /tmp/test.tar
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  

    - name: Running the Docker Image
      run: |
         echo "Running Docker Image"
          docker run -dit test_image:latest cat install.sh

        
