on:
#   pull_request:
  push:
    branches:
      - main
      - master
      - release*
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2


    - name: Build and push
      uses: docker/build-push-action@v4
      with:
       push: false
       tags: |
              test:latest
              outputs: type=docker,dest=/tmp/test.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: docker-image
          path: /tmp/test.tar
    
          
        
