on:
#   pull_request:
  push:
    branches:
      - main
      - master
      - release*
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: installing python dependencies
      run: |
          chmod +x ./install.sh
          bash ./install.sh
          
        
